services:
  keyclaok:
    image: quay.io/keycloak/keycloak:18.0.1
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev