logging:
  level:
    root: info
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/demo
          jwk-set-uri: http://localhost:8081/realms/demo/protocol/openid-connect/certs